/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and start a session */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new pair
         * @description Rotates the token. A token presented long after it was rotated is treated as reuse and ends every session for that user; presenting it within the grace window is treated as a concurrent refresh and simply issues a new pair.
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a refresh token */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Node metadata with breadcrumbs and what the caller may do */
        get: operations["NodesController_detail"];
        put?: never;
        post?: never;
        /**
         * Delete a node and everything under it
         * @description Storage objects are queued for removal in the same transaction and deleted afterwards.
         */
        delete: operations["NodesController_remove"];
        options?: never;
        head?: never;
        /** Rename. Renaming a data room’s root renames the room. */
        patch: operations["NodesController_rename"];
        trace?: never;
    };
    "/nodes/{id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One page of a folder’s contents
         * @description Keyset pagination: pass the previous page’s cursor. Ordered folders first, then by name, case-insensitively.
         */
        get: operations["NodesController_children"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Totals for everything under this node
         * @description Used by the folder header and by the delete confirmation, so the warning states what will actually be removed.
         */
        get: operations["NodesController_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NodesController_createFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NodesController_move"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data rooms owned by the caller */
        get: operations["DataRoomsController_list"];
        put?: never;
        post: operations["DataRoomsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DataRoomsController_get"];
        put?: never;
        post?: never;
        /**
         * Delete a data room and everything in it
         * @description Runs through the same subtree deletion as any folder, so blobs are queued too.
         */
        delete: operations["DataRoomsController_remove"];
        options?: never;
        head?: never;
        /**
         * Rename a data room
         * @description Renames the room’s root node, which is where the name lives.
         */
        patch: operations["DataRoomsController_rename"];
        trace?: never;
    };
    "/nodes/{id}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who can currently see this item */
        get: operations["SharesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}/shares/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create or return the public link for an item
         * @description Idempotent: an item has at most one active link, so pressing share twice cannot leave a second URL that the owner never sees and cannot revoke.
         */
        post: operations["SharesController_createLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shares/links/{linkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a public link
         * @description Takes effect on the next request: access is re-resolved every time and never cached in a session.
         */
        delete: operations["SharesController_revokeLink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}/shares/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Give a specific person read access
         * @description By email address, so someone who has not registered yet can be invited; access resolves when they sign in. Re-inviting a revoked person reinstates the same grant.
         */
        post: operations["SharesController_grant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shares/grants/{grantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["SharesController_revokeGrant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What a public link points at
         * @description Public by design — the token is the credential. Answers only about the shared item: naming its data room or its ancestors would defeat truncating them everywhere else.
         */
        get: operations["SharesController_resolveLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared-with-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Items other people have shared with the caller */
        get: operations["SharesController_sharedWithMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{grantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve an invitation link
         * @description No email is sent by this service, so the owner copies a link and passes it on. It resolves only for the invited address.
         */
        get: operations["SharesController_invite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get signed URLs for a batch of files
         * @description The browser then PUTs each file directly to storage, so bytes never pass through this API and upload throughput does not depend on it. Any name collisions are reported here, before the bytes are sent.
         */
        post: operations["UploadsController_presign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an uploaded object as a file
         * @description Idempotent: repeating a completed upload returns the same result. A conflict does not consume the upload, so the client can answer differently without sending the bytes again.
         */
        post: operations["UploadsController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{nodeId}/preview-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A short-lived signed URL for viewing or downloading the current version
         * @description Returns JSON rather than redirecting: the client knows when the URL expires and can fetch a new one before it does, and no proxy layer has to be taught to forward a Location header.
         */
        get: operations["FilesController_previewUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{nodeId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version history
         * @description Owners only. The history names the people who uploaded each version, which is internal information about the seller’s team rather than something a guest needs.
         */
        get: operations["FilesController_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example dana@acme.com */
            email: string;
            /** @example Password123! */
            password: string;
            /** @example Dana Owner */
            displayName: string;
        };
        UserDto: {
            id: string;
            email: string;
            displayName: string;
        };
        SessionDto: {
            user: components["schemas"]["UserDto"];
            accessToken: string;
            /** @description Store server-side; the browser never sees this directly. */
            refreshToken: string;
            /** @description Seconds until the access token expires. */
            accessTokenExpiresInSeconds: number;
        };
        LoginDto: {
            /** @example dana@acme.com */
            email: string;
            /** @example Password123! */
            password: string;
        };
        RefreshDto: {
            /** @description Opaque refresh token issued by login or a previous refresh */
            refreshToken: string;
        };
        NodeDto: {
            id: string;
            dataRoomId: string;
            parentId: string | null;
            /** @enum {string} */
            type: "FOLDER" | "FILE";
            name: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Current version size */
            sizeBytes?: number | null;
            mimeType?: string | null;
        };
        BreadcrumbDto: {
            id: string;
            name: string;
        };
        CapabilitiesDto: {
            canCreate: boolean;
            canRename: boolean;
            canMove: boolean;
            canDelete: boolean;
            canUpload: boolean;
            canShare: boolean;
            canViewVersionHistory: boolean;
        };
        NodeDetailDto: {
            node: components["schemas"]["NodeDto"];
            /** @description Root first; truncated for guests */
            breadcrumbs: components["schemas"]["BreadcrumbDto"][];
            capabilities: components["schemas"]["CapabilitiesDto"];
        };
        ChildrenPageDto: {
            items: components["schemas"]["NodeDto"][];
            /** @description Absent when this is the last page */
            nextCursor?: string;
        };
        SubtreeStatsDto: {
            folderCount: number;
            fileCount: number;
            /** @description Sum of current versions — the logical size */
            totalSizeBytes: number;
        };
        CreateFolderDto: {
            parentId: string;
            /** @example 03 Legal */
            name: string;
            /**
             * @description "fail" reports a conflict so the UI can ask; "rename" keeps both by appending a counter.
             * @default fail
             * @enum {string}
             */
            onConflict: "fail" | "rename";
        };
        RenameNodeDto: {
            name: string;
            /**
             * @default fail
             * @enum {string}
             */
            onConflict: "fail" | "rename";
        };
        MoveNodeDto: {
            targetParentId: string;
            /**
             * @default fail
             * @enum {string}
             */
            onConflict: "fail" | "rename";
        };
        DataRoomDto: {
            id: string;
            /** @description The name of the room’s root node */
            name: string;
            /** @description Open this node to browse the room */
            rootNodeId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateDataRoomDto: {
            /** @example Project Beacon */
            name: string;
        };
        ShareLinkDto: {
            id: string;
            /** @description Build the public URL as <app>/s/<token> */
            token: string;
            nodeId: string;
            expiresAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ShareGrantDto: {
            id: string;
            nodeId: string;
            email: string;
            /** Format: date-time */
            createdAt: string;
        };
        NodeSharesDto: {
            /** @description At most one active link per item, so the interface has one thing to copy. */
            link?: components["schemas"]["ShareLinkDto"] | null;
            grants: components["schemas"]["ShareGrantDto"][];
        };
        CreateShareLinkDto: {
            /** @description Optional expiry. Without one the link lives until it is revoked. */
            expiresAt?: string;
        };
        CreateShareGrantDto: {
            /**
             * @description The invitee does not need an account yet: access is resolved by address when they sign in.
             * @example counsel@beacon.com
             */
            email: string;
        };
        SharedLinkContextDto: {
            nodeId: string;
            nodeName: string;
            /** @enum {string} */
            nodeType: "FOLDER" | "FILE";
        };
        SharedWithMeItemDto: {
            nodeId: string;
            nodeName: string;
            /** @enum {string} */
            nodeType: "FOLDER" | "FILE";
            dataRoomId: string;
            /** @description Who shared it */
            sharedBy: string;
            /** Format: date-time */
            sharedAt: string;
        };
        PresignItemDto: {
            /** @example Q1 2026 Accounts.pdf */
            fileName: string;
            /** @example application/pdf */
            mimeType: string;
            /** @description Declared size; verified against the stored object afterwards */
            sizeBytes: number;
        };
        PresignBatchDto: {
            parentId: string;
            /** @description Batched deliberately: one request per file would collide with this API’s own rate limit the first time someone drags in a folder. */
            items: components["schemas"]["PresignItemDto"][];
        };
        UploadConflictDto: {
            existingNodeId: string;
            /**
             * @description A collision with a folder cannot be resolved by adding a version — the UI needs this to avoid offering a dead option.
             * @enum {string}
             */
            existingType: "FOLDER" | "FILE";
            /** @description Versions the existing file already has */
            versionCount: number;
        };
        PresignedItemDto: {
            intentId: string;
            uploadUrl: string;
            /** @description Send exactly this Content-Type or the signature will not match */
            contentType: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description Advisory: reported before the bytes are sent so the user is asked first. */
            conflict?: components["schemas"]["UploadConflictDto"];
        };
        PresignBatchResultDto: {
            items: components["schemas"]["PresignedItemDto"][];
        };
        CompleteUploadDto: {
            intentId: string;
            /**
             * @description "newVersion" adds a version to the colliding file instead of creating a second one.
             * @default fail
             * @enum {string}
             */
            onConflict: "fail" | "rename" | "newVersion";
        };
        UploadResultDto: {
            node: components["schemas"]["NodeDto"];
            versionNumber: number;
            sizeBytes: number;
        };
        PreviewUrlDto: {
            /** @description Short-lived, signed; fetch a new one before it expires */
            url: string;
            /** Format: date-time */
            expiresAt: string;
            /** @enum {string} */
            disposition: "inline" | "attachment";
            fileName: string;
            mimeType: string;
            sizeBytes: number;
        };
        FileVersionDto: {
            id: string;
            versionNumber: number;
            isCurrent: boolean;
            sizeBytes: number;
            /** Format: date-time */
            createdAt: string;
            /** @description Who uploaded it — owners only */
            createdBy: string;
        };
        HealthResponse: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    NodesController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetailDto"];
                };
            };
        };
    };
    NodesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NodesController_rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameNodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDto"];
                };
            };
        };
    };
    NodesController_children: {
        parameters: {
            query?: {
                /** @description Opaque cursor from the previous page */
                cursor?: string;
                limit?: number;
                type?: "FOLDER" | "FILE";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildrenPageDto"];
                };
            };
        };
    };
    NodesController_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubtreeStatsDto"];
                };
            };
        };
    };
    NodesController_createFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDto"];
                };
            };
        };
    };
    NodesController_move: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveNodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDto"];
                };
            };
        };
    };
    DataRoomsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRoomDto"][];
                };
            };
        };
    };
    DataRoomsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDataRoomDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRoomDto"];
                };
            };
        };
    };
    DataRoomsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRoomDto"];
                };
            };
        };
    };
    DataRoomsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DataRoomsController_rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameNodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRoomDto"];
                };
            };
        };
    };
    SharesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeSharesDto"];
                };
            };
        };
    };
    SharesController_createLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShareLinkDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareLinkDto"];
                };
            };
        };
    };
    SharesController_revokeLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SharesController_grant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShareGrantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareGrantDto"];
                };
            };
        };
    };
    SharesController_revokeGrant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SharesController_resolveLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedLinkContextDto"];
                };
            };
        };
    };
    SharesController_sharedWithMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedWithMeItemDto"][];
                };
            };
        };
    };
    SharesController_invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedWithMeItemDto"];
                };
            };
        };
    };
    UploadsController_presign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignBatchDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignBatchResultDto"];
                };
            };
        };
    };
    UploadsController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteUploadDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResultDto"];
                };
            };
        };
    };
    FilesController_previewUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewUrlDto"];
                };
            };
        };
    };
    FilesController_versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileVersionDto"][];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
